apiVersion: v1
kind: PersistentVolume
metadata:
  name: aoc-leaderboard-scraper
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data

